# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Spectrum CE Blog
email: spectrumpci@gmail.com
description: # this means to ignore newlines until "baseurl:"
    Os projetos da Spectrum CE Ltda estão concentrados na interface entre
    hardware e software tais como sistemas embarcados com sensores de 
    ambiente e atuadores. Inicialmente focados na automação residencial e
    agrícola (controle e monitoramento de irrigação).
    #  Novidades sobre a Spectrum vão ser postadas aqui, tais como marcos de 
    # desenvolvimento de nossos projetos.
baseurl: /gh-pages # the subpath of your site, e.g. /blog
url: "http://spectrumpci.com.br" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  spectrumpci

# Build settings
markdown: kramdown
# markdown: redcarpet
